// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProActive2508.Data;

#nullable disable

namespace ProActive2508.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260107110708_anjaupdatemigration")]
    partial class anjaupdatemigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Antwort", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Datum")
                        .HasColumnType("datetime2");

                    b.Property<int>("FrageId")
                        .HasColumnType("int");

                    b.Property<int>("ProjektId")
                        .HasColumnType("int");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FrageId");

                    b.HasIndex("ProjektId");

                    b.ToTable("Antwort", (string)null);
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Aufgabe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Aufgabenbeschreibung")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<int>("Erledigt")
                        .HasColumnType("int");

                    b.Property<int>("ErstellVon")
                        .HasColumnType("int");

                    b.Property<DateTime>("Faellig")
                        .HasColumnType("date");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<int?>("ProjektId")
                        .HasColumnType("int");

                    b.Property<int?>("ProjektPhasenId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("ProjektId");

                    b.HasIndex("ProjektPhasenId");

                    b.HasIndex("Phase", "Faellig");

                    b.ToTable("Aufgaben", (string)null);
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Benutzer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Abteilung")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Personalnummer")
                        .HasColumnType("int");

                    b.Property<string>("Stufe")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("Verfuegbarkeit")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Personalnummer")
                        .IsUnique();

                    b.ToTable("Benutzer", (string)null);
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Frage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("KategorieId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("KategorieId");

                    b.ToTable("Frage", (string)null);
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Allergen", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Kuerzel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("Kuerzel")
                        .IsUnique();

                    b.ToTable("Allergene");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Gericht", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gerichtname")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("Gerichtname")
                        .IsUnique();

                    b.ToTable("Gerichte");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.GerichtAllergen", b =>
                {
                    b.Property<int>("GerichtId")
                        .HasColumnType("int");

                    b.Property<int>("AllergenId")
                        .HasColumnType("int");

                    b.HasKey("GerichtId", "AllergenId");

                    b.HasIndex("AllergenId");

                    b.ToTable("GerichtAllergene");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Menueplan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GerichtId")
                        .HasColumnType("int");

                    b.Property<int>("MenueplanTagId")
                        .HasColumnType("int");

                    b.Property<byte>("PositionNr")
                        .HasColumnType("tinyint");

                    b.HasKey("Id");

                    b.HasIndex("GerichtId");

                    b.HasIndex("MenueplanTagId", "PositionNr")
                        .IsUnique();

                    b.ToTable("Menueplaene", t =>
                        {
                            t.HasCheckConstraint("CK_Menueplan_Position", "[PositionNr] IN (1,2)");
                        });
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.MenueplanTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Tag")
                        .HasColumnType("date");

                    b.Property<int?>("Woche")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Tag")
                        .IsUnique();

                    b.ToTable("MenueplanTage");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Preisverlauf", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("GerichtId")
                        .HasColumnType("int");

                    b.Property<DateTime>("GueltigAb")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Preis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("GerichtId", "GueltigAb")
                        .IsUnique();

                    b.ToTable("Preisverlaeufe");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Vorbestellung", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("BestelltAm")
                        .HasColumnType("datetime2");

                    b.Property<int>("EintragId")
                        .HasColumnType("int");

                    b.Property<int>("MenueplanTagId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EintragId");

                    b.HasIndex("MenueplanTagId");

                    b.HasIndex("BenutzerId", "EintragId")
                        .IsUnique();

                    b.HasIndex("BenutzerId", "MenueplanTagId")
                        .IsUnique();

                    b.ToTable("Vorbestellungen");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Meilenstein", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Meilenstein", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bezeichnung = "Quotation"
                        },
                        new
                        {
                            Id = 2,
                            Bezeichnung = "Program Kick-Off"
                        },
                        new
                        {
                            Id = 3,
                            Bezeichnung = "Prototype Design"
                        },
                        new
                        {
                            Id = 4,
                            Bezeichnung = "Production Design"
                        },
                        new
                        {
                            Id = 5,
                            Bezeichnung = "Off Process Tools"
                        },
                        new
                        {
                            Id = 6,
                            Bezeichnung = "Customer PPAP"
                        },
                        new
                        {
                            Id = 7,
                            Bezeichnung = "Production Launch"
                        },
                        new
                        {
                            Id = 8,
                            Bezeichnung = "Productio Transition"
                        },
                        new
                        {
                            Id = 9,
                            Bezeichnung = "End"
                        });
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Phase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Bezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Kurzbezeichnung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Phase", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Bezeichnung = "Quotation",
                            Kurzbezeichnung = "P0"
                        },
                        new
                        {
                            Id = 2,
                            Bezeichnung = "Program Preparation and Kick-Off",
                            Kurzbezeichnung = "P1"
                        },
                        new
                        {
                            Id = 3,
                            Bezeichnung = "Prototype Design",
                            Kurzbezeichnung = "P2"
                        },
                        new
                        {
                            Id = 4,
                            Bezeichnung = "Production Design",
                            Kurzbezeichnung = "P3"
                        },
                        new
                        {
                            Id = 5,
                            Bezeichnung = "Off Process Samples",
                            Kurzbezeichnung = "P4"
                        },
                        new
                        {
                            Id = 6,
                            Bezeichnung = "Customer PPAP Preparation",
                            Kurzbezeichnung = "P5"
                        },
                        new
                        {
                            Id = 7,
                            Bezeichnung = "Production Launch",
                            Kurzbezeichnung = "P6"
                        },
                        new
                        {
                            Id = 8,
                            Bezeichnung = "End of Regular Production & Transition to service",
                            Kurzbezeichnung = "P7"
                        },
                        new
                        {
                            Id = 9,
                            Bezeichnung = "Product Close-Out",
                            Kurzbezeichnung = "P8"
                        });
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.PhaseMeilenstein", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Erreichtdatum")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenehmigerbenutzerId")
                        .HasColumnType("int");

                    b.Property<int>("MeilensteinId")
                        .HasColumnType("int");

                    b.Property<int>("ProjektphasenId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Zieldatum")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("GenehmigerbenutzerId");

                    b.HasIndex("MeilensteinId");

                    b.HasIndex("ProjektphasenId");

                    b.ToTable("PhaseMeilenstein", (string)null);
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Projekt", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AufgabeId")
                        .HasColumnType("int");

                    b.Property<int>("AuftraggeberId")
                        .HasColumnType("int");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<int>("Phase")
                        .HasColumnType("int");

                    b.Property<int?>("ProblemId")
                        .HasColumnType("int");

                    b.Property<string>("Projektbeschreibung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjektleiterId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuftraggeberId");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("ProjektleiterId");

                    b.HasIndex("Status", "Phase");

                    b.ToTable("Projekte", (string)null);
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.ProjektBenutzer", b =>
                {
                    b.Property<int>("ProjektId")
                        .HasColumnType("int");

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.HasKey("ProjektId", "BenutzerId");

                    b.HasIndex("BenutzerId");

                    b.ToTable("ProjektBenutzer", (string)null);
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.ProjektPhase", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("Abschlussdatum")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Notizen")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PhasenId")
                        .HasColumnType("int");

                    b.Property<int>("ProjekteId")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerantwortlicherbenutzerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PhasenId");

                    b.HasIndex("ProjekteId");

                    b.HasIndex("VerantwortlicherbenutzerId");

                    b.ToTable("ProjektPhase", (string)null);
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.ProjektPhasenMA", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BenutzerId")
                        .HasColumnType("int");

                    b.Property<int>("ProjektphasenId")
                        .HasColumnType("int");

                    b.Property<string>("Rolle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Zustandigkeit")
                        .IsUnicode(false)
                        .HasColumnType("varchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BenutzerId");

                    b.HasIndex("ProjektphasenId");

                    b.ToTable("ProjektPhasenMA", (string)null);
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.UmfrageKategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .IsUnicode(false)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.ToTable("UmfrageKategorie", null, t =>
                        {
                            t.HasCheckConstraint("CK_UmfrageKategorie_Name_NotEmpty", "LEN([Name]) > 0");
                        });
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Antwort", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Frage", "Frage")
                        .WithMany("Antworten")
                        .HasForeignKey("FrageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Projekt", "Projekt")
                        .WithMany("Antworten")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Frage");

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Aufgabe", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Benutzer", "Benutzer")
                        .WithMany("Aufgaben")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Projekt", "Projekt")
                        .WithMany("Aufgaben")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ProActive2508.Models.Entity.Anja.ProjektPhase", "ProjektPhase")
                        .WithMany("Aufgaben")
                        .HasForeignKey("ProjektPhasenId");

                    b.Navigation("Benutzer");

                    b.Navigation("Projekt");

                    b.Navigation("ProjektPhase");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Frage", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.UmfrageKategorie", "Kategorie")
                        .WithMany("Fragen")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorie");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.GerichtAllergen", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Kantine.Allergen", "Allergen")
                        .WithMany("GerichtAllergene")
                        .HasForeignKey("AllergenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Kantine.Gericht", "Gericht")
                        .WithMany("GerichtAllergene")
                        .HasForeignKey("GerichtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Allergen");

                    b.Navigation("Gericht");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Menueplan", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Kantine.Gericht", "Gericht")
                        .WithMany()
                        .HasForeignKey("GerichtId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Kantine.MenueplanTag", "MenueplanTag")
                        .WithMany("Eintraege")
                        .HasForeignKey("MenueplanTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gericht");

                    b.Navigation("MenueplanTag");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Preisverlauf", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Kantine.Gericht", "Gericht")
                        .WithMany("Preisverlaeufe")
                        .HasForeignKey("GerichtId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Gericht");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Vorbestellung", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Benutzer", "Benutzer")
                        .WithMany()
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Kantine.Menueplan", "Eintrag")
                        .WithMany()
                        .HasForeignKey("EintragId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Kantine.MenueplanTag", "MenueplanTag")
                        .WithMany()
                        .HasForeignKey("MenueplanTagId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");

                    b.Navigation("Eintrag");

                    b.Navigation("MenueplanTag");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.PhaseMeilenstein", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Benutzer", "GenehmigerBenutzer")
                        .WithMany("GenehmigtePhaseMeilensteine")
                        .HasForeignKey("GenehmigerbenutzerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Meilenstein", "Meilenstein")
                        .WithMany("PhaseMeilensteine")
                        .HasForeignKey("MeilensteinId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.ProjektPhase", "ProjektPhase")
                        .WithMany("PhaseMeilensteine")
                        .HasForeignKey("ProjektphasenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GenehmigerBenutzer");

                    b.Navigation("Meilenstein");

                    b.Navigation("ProjektPhase");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Projekt", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Benutzer", "Auftraggeber")
                        .WithMany("ProjekteAlsAuftraggeber")
                        .HasForeignKey("AuftraggeberId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Benutzer", "Owner")
                        .WithMany("ProjekteAlsOwner")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Benutzer", "Projektleiter")
                        .WithMany("ProjekteAlsProjektleiter")
                        .HasForeignKey("ProjektleiterId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Auftraggeber");

                    b.Navigation("Owner");

                    b.Navigation("Projektleiter");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.ProjektBenutzer", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Benutzer", "Benutzer")
                        .WithMany("ProjektBenutzer")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Projekt", "Projekt")
                        .WithMany("ProjektBenutzer")
                        .HasForeignKey("ProjektId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");

                    b.Navigation("Projekt");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.ProjektPhase", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Phase", "Phase")
                        .WithMany("ProjektPhasen")
                        .HasForeignKey("PhasenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Projekt", "Projekt")
                        .WithMany("ProjektPhasen")
                        .HasForeignKey("ProjekteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.Benutzer", "VerantwortlicherBenutzer")
                        .WithMany("ProjektPhasenAlsVerantwortlicher")
                        .HasForeignKey("VerantwortlicherbenutzerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Phase");

                    b.Navigation("Projekt");

                    b.Navigation("VerantwortlicherBenutzer");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.ProjektPhasenMA", b =>
                {
                    b.HasOne("ProActive2508.Models.Entity.Anja.Benutzer", "Benutzer")
                        .WithMany("ProjektPhasenMitarbeiter")
                        .HasForeignKey("BenutzerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ProActive2508.Models.Entity.Anja.ProjektPhase", "ProjektPhase")
                        .WithMany("ProjektPhasenMitarbeiter")
                        .HasForeignKey("ProjektphasenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Benutzer");

                    b.Navigation("ProjektPhase");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Benutzer", b =>
                {
                    b.Navigation("Aufgaben");

                    b.Navigation("GenehmigtePhaseMeilensteine");

                    b.Navigation("ProjektBenutzer");

                    b.Navigation("ProjektPhasenAlsVerantwortlicher");

                    b.Navigation("ProjektPhasenMitarbeiter");

                    b.Navigation("ProjekteAlsAuftraggeber");

                    b.Navigation("ProjekteAlsOwner");

                    b.Navigation("ProjekteAlsProjektleiter");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Frage", b =>
                {
                    b.Navigation("Antworten");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Allergen", b =>
                {
                    b.Navigation("GerichtAllergene");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.Gericht", b =>
                {
                    b.Navigation("GerichtAllergene");

                    b.Navigation("Preisverlaeufe");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Kantine.MenueplanTag", b =>
                {
                    b.Navigation("Eintraege");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Meilenstein", b =>
                {
                    b.Navigation("PhaseMeilensteine");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Phase", b =>
                {
                    b.Navigation("ProjektPhasen");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.Projekt", b =>
                {
                    b.Navigation("Antworten");

                    b.Navigation("Aufgaben");

                    b.Navigation("ProjektBenutzer");

                    b.Navigation("ProjektPhasen");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.ProjektPhase", b =>
                {
                    b.Navigation("Aufgaben");

                    b.Navigation("PhaseMeilensteine");

                    b.Navigation("ProjektPhasenMitarbeiter");
                });

            modelBuilder.Entity("ProActive2508.Models.Entity.Anja.UmfrageKategorie", b =>
                {
                    b.Navigation("Fragen");
                });
#pragma warning restore 612, 618
        }
    }
}
